# Generated by Django 2.0.4 on 2018-06-07 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_graphomaniac', '0002_note_count_unique_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
