# Generated by Django 2.0.4 on 2018-06-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_graphomaniac', '0004_note_date'),
    ]

    operations = [

    ]
