# Generated by Django 2.0.4 on 2018-06-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_graphomaniac', '0005_auto_20180607_0415'),
    ]

    operations = [

    ]
