# Generated by Django 2.0.4 on 2018-06-07 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes_graphomaniac', '0006_auto_20180607_0430'),
    ]

    operations = [

    ]
