# Generated by Django 2.0.4 on 2018-06-07 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes_graphomaniac', '0007_auto_20180607_1153'),
    ]

    operations = [

    ]
