# Generated by Django 2.0.4 on 2018-06-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_graphomaniac', '0009_auto_20180608_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
